file = '../assets/options.txt'
wall_image = '../assets/murillo.png'
ground_image = '../assets/ground.png'
character = '../assets/character.png'
width = 1600
height = 900
tilesize = 25
blue = (0, 0, 255)
red = (255, 0, 0)
black = (0, 0, 0)
fps = 60
player_layer = 1
