file = '../assets/options.txt'
wall_image = '../assets/murillo.png'
terrain_sprites = '../assets/terrain_sprites.png'
character_sprites = '../assets/character_sprites.png'
objects_sprites = '../assets/objects_sprites.png'
width = 1800
height = 900
tilesize = 25
player_speed = 2
heart_healing = 50
water_damage = 2
player_health_point = 100
blue = (0, 0, 255)
red = (255, 0, 0)
black = (0, 0, 0)
fps = 60
player_layer = 3
wall_layer = 2
ground_layer = 1
