file = '../assets/options.txt'
wall_image = '../assets/murillo.png'
terrain_sprites = '../assets/terrain_sprites.png'
character_sprites = '../assets/character_sprites.png'
dive_sprites = '../assets/dive_sprites.png'
music_theme = '../assets/theme.mp3'
objects_sprites = '../assets/objects_sprites.png'
font = '../assets/8-bit-hud.ttf'
background_image = '../assets/background.jpg'
gameover_image = '../assets/gameover.jpg'
font_size = 25
width = 1600
height = 950
tilesize = 25
player_speed = 2
heart_healing = 50
water_damage = 2
max_hp = 100
t_pressed = False
b_pressed = False
player_health_point = 100
blue = (0, 0, 255)
red = (255, 0, 0)
black = (0, 0, 0)
white = (255, 255, 255)
fps = 60
player_layer = 3
wall_layer = 2
ground_layer = 1
